
network: network.yml

layers:

  - name: development
    image: jordanspieth [development] hvm [1422647259]
    instanceType: m3.large
    rolePolicies:
      - beam-server-readonly
      - create-describe-amis
      - s3-full-access

    securityRules:
      - development
      - operations

    provisioners:
    - type: knife-solo
      cookbookPath: ../chef
      recipe: jordanspieth::development

    placements:
      - subnetType: development
        sizePerSubnet: 1
        hostnames:
          - "upgrade-dev.jordanspieth.psdops.com."
          - "*.upgrade-dev.jordanspieth.psdops.com."
          - "upgrade-jenkins.jordanspieth.psdops.com."
